/**
 * @archeusllc/types - API Client Types for Band Together
 *
 * This file is auto-generated by the API server.
 * Do not edit manually.
 *
 * Generated from: api/src/index.ts
 * Run: cd api && bun run generate
 */

export type App = any;
